version: 2
jobs:
  build:
    docker:
      - image: hovhannisyangurgen/maven-base:latest
    working_directory: ~/karate-circleci
    steps:
      - checkout
      - run:
          name: 'Run tests'
          command: mvn test
